name: Build App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Inject .NET Framework 4.5 Reference Assemblies
      shell: powershell
      run: |
        # Скачиваем официальный пакет таргетов .NET 4.5 в виде zip
        Invoke-WebRequest -Uri "https://nuget.org" -OutFile "net45.zip"
        # Распаковываем его
        Expand-Archive -Path "net45.zip" -DestinationPath "net45_extracted"
        # Создаем целевую системную директорию, куда обращается MSBuild
        New-Item -ItemType Directory -Force -Path "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5"
        # Копируем туда файлы конфигурации фреймворка
        Copy-Item -Path "net45_extracted\build\.NETFramework\v4.5\*" -Destination "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5" -Recurse -Force
        echo "Successfully injected .NET 4.5 targeting pack!"

    - name: Restore NuGet Packages
      run: nuget restore SeaGateQVM.csproj || echo "No NuGet packages to restore"

    - name: Build App with VS Build
      run: |
        msbuild SeaGateQVM.csproj /p:Configuration=Release /p:Platform="AnyCPU"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Built-App
        path: |
          **/bin/Release/
          **/*.exe
          **/*.xap
          **/*.appx
