name: Build App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild and .NET Tools
      uses: microsoft/setup-msbuild@v2

    - name: Setup .NET Framework Developer Pack
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x' # Нужен для работы внутренних утилит восстановления пакетов

    - name: Restore NuGet Packages
      run: nuget restore SeaGateQVM.csproj || echo "No NuGet packages to restore"

    - name: Build App with VS Build
      run: |
        msbuild SeaGateQVM.csproj /p:Configuration=Release /p:Platform="AnyCPU" /p:TargetFrameworkVersion="v4.5"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Built-App
        path: |
          **/bin/Release/
          **/*.exe
          **/*.xap
          **/*.appx
